# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gustavo/Desktop/projects/gitbox/gbui

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gustavo/Desktop/projects/gitbox/gbui

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gustavo/Desktop/projects/gitbox/gbui/CMakeFiles /home/gustavo/Desktop/projects/gitbox/gbui//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gustavo/Desktop/projects/gitbox/gbui/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gbui

# Build rule for target.
gbui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbui
.PHONY : gbui

# fast build rule for target.
gbui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/build
.PHONY : gbui/fast

#=============================================================================
# Target rules for targets named gbui_meta

# Build rule for target.
gbui_meta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbui_meta
.PHONY : gbui_meta

# fast build rule for target.
gbui_meta/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui_meta.dir/build.make CMakeFiles/gbui_meta.dir/build
.PHONY : gbui_meta/fast

#=============================================================================
# Target rules for targets named gbui_tests

# Build rule for target.
gbui_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbui_tests
.PHONY : gbui_tests

# fast build rule for target.
gbui_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/gbui_tests.dir/build.make tests/CMakeFiles/gbui_tests.dir/build
.PHONY : gbui_tests/fast

#=============================================================================
# Target rules for targets named gbui_panel

# Build rule for target.
gbui_panel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbui_panel
.PHONY : gbui_panel

# fast build rule for target.
gbui_panel/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/gbui_panel.dir/build.make examples/CMakeFiles/gbui_panel.dir/build
.PHONY : gbui_panel/fast

#=============================================================================
# Target rules for targets named gbui_gallery

# Build rule for target.
gbui_gallery: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbui_gallery
.PHONY : gbui_gallery

# fast build rule for target.
gbui_gallery/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/gbui_gallery.dir/build.make examples/CMakeFiles/gbui_gallery.dir/build
.PHONY : gbui_gallery/fast

#=============================================================================
# Target rules for targets named gbui_app

# Build rule for target.
gbui_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbui_app
.PHONY : gbui_app

# fast build rule for target.
gbui_app/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/gbui_app.dir/build.make examples/CMakeFiles/gbui_app.dir/build
.PHONY : gbui_app/fast

#=============================================================================
# Target rules for targets named gbui_controls

# Build rule for target.
gbui_controls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbui_controls
.PHONY : gbui_controls

# fast build rule for target.
gbui_controls/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/gbui_controls.dir/build.make examples/CMakeFiles/gbui_controls.dir/build
.PHONY : gbui_controls/fast

#=============================================================================
# Target rules for targets named gbui_demos

# Build rule for target.
gbui_demos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbui_demos
.PHONY : gbui_demos

# fast build rule for target.
gbui_demos/fast:
	$(MAKE) $(MAKESILENT) -f demos/CMakeFiles/gbui_demos.dir/build.make demos/CMakeFiles/gbui_demos.dir/build
.PHONY : gbui_demos/fast

#=============================================================================
# Target rules for targets named gbui_demo

# Build rule for target.
gbui_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbui_demo
.PHONY : gbui_demo

# fast build rule for target.
gbui_demo/fast:
	$(MAKE) $(MAKESILENT) -f demos/CMakeFiles/gbui_demo.dir/build.make demos/CMakeFiles/gbui_demo.dir/build
.PHONY : gbui_demo/fast

src/a11y/role.o: src/a11y/role.cpp.o
.PHONY : src/a11y/role.o

# target to build an object file
src/a11y/role.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/a11y/role.cpp.o
.PHONY : src/a11y/role.cpp.o

src/a11y/role.i: src/a11y/role.cpp.i
.PHONY : src/a11y/role.i

# target to preprocess a source file
src/a11y/role.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/a11y/role.cpp.i
.PHONY : src/a11y/role.cpp.i

src/a11y/role.s: src/a11y/role.cpp.s
.PHONY : src/a11y/role.s

# target to generate assembly for a file
src/a11y/role.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/a11y/role.cpp.s
.PHONY : src/a11y/role.cpp.s

src/a11y/tree.o: src/a11y/tree.cpp.o
.PHONY : src/a11y/tree.o

# target to build an object file
src/a11y/tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/a11y/tree.cpp.o
.PHONY : src/a11y/tree.cpp.o

src/a11y/tree.i: src/a11y/tree.cpp.i
.PHONY : src/a11y/tree.i

# target to preprocess a source file
src/a11y/tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/a11y/tree.cpp.i
.PHONY : src/a11y/tree.cpp.i

src/a11y/tree.s: src/a11y/tree.cpp.s
.PHONY : src/a11y/tree.s

# target to generate assembly for a file
src/a11y/tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/a11y/tree.cpp.s
.PHONY : src/a11y/tree.cpp.s

src/anim/animator.o: src/anim/animator.cpp.o
.PHONY : src/anim/animator.o

# target to build an object file
src/anim/animator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/anim/animator.cpp.o
.PHONY : src/anim/animator.cpp.o

src/anim/animator.i: src/anim/animator.cpp.i
.PHONY : src/anim/animator.i

# target to preprocess a source file
src/anim/animator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/anim/animator.cpp.i
.PHONY : src/anim/animator.cpp.i

src/anim/animator.s: src/anim/animator.cpp.s
.PHONY : src/anim/animator.s

# target to generate assembly for a file
src/anim/animator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/anim/animator.cpp.s
.PHONY : src/anim/animator.cpp.s

src/anim/easing.o: src/anim/easing.cpp.o
.PHONY : src/anim/easing.o

# target to build an object file
src/anim/easing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/anim/easing.cpp.o
.PHONY : src/anim/easing.cpp.o

src/anim/easing.i: src/anim/easing.cpp.i
.PHONY : src/anim/easing.i

# target to preprocess a source file
src/anim/easing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/anim/easing.cpp.i
.PHONY : src/anim/easing.cpp.i

src/anim/easing.s: src/anim/easing.cpp.s
.PHONY : src/anim/easing.s

# target to generate assembly for a file
src/anim/easing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/anim/easing.cpp.s
.PHONY : src/anim/easing.cpp.s

src/core/color.o: src/core/color.cpp.o
.PHONY : src/core/color.o

# target to build an object file
src/core/color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/core/color.cpp.o
.PHONY : src/core/color.cpp.o

src/core/color.i: src/core/color.cpp.i
.PHONY : src/core/color.i

# target to preprocess a source file
src/core/color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/core/color.cpp.i
.PHONY : src/core/color.cpp.i

src/core/color.s: src/core/color.cpp.s
.PHONY : src/core/color.s

# target to generate assembly for a file
src/core/color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/core/color.cpp.s
.PHONY : src/core/color.cpp.s

src/core/json.o: src/core/json.cpp.o
.PHONY : src/core/json.o

# target to build an object file
src/core/json.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/core/json.cpp.o
.PHONY : src/core/json.cpp.o

src/core/json.i: src/core/json.cpp.i
.PHONY : src/core/json.i

# target to preprocess a source file
src/core/json.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/core/json.cpp.i
.PHONY : src/core/json.cpp.i

src/core/json.s: src/core/json.cpp.s
.PHONY : src/core/json.s

# target to generate assembly for a file
src/core/json.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/core/json.cpp.s
.PHONY : src/core/json.cpp.s

src/core/path.o: src/core/path.cpp.o
.PHONY : src/core/path.o

# target to build an object file
src/core/path.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/core/path.cpp.o
.PHONY : src/core/path.cpp.o

src/core/path.i: src/core/path.cpp.i
.PHONY : src/core/path.i

# target to preprocess a source file
src/core/path.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/core/path.cpp.i
.PHONY : src/core/path.cpp.i

src/core/path.s: src/core/path.cpp.s
.PHONY : src/core/path.s

# target to generate assembly for a file
src/core/path.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/core/path.cpp.s
.PHONY : src/core/path.cpp.s

src/input/interaction.o: src/input/interaction.cpp.o
.PHONY : src/input/interaction.o

# target to build an object file
src/input/interaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/input/interaction.cpp.o
.PHONY : src/input/interaction.cpp.o

src/input/interaction.i: src/input/interaction.cpp.i
.PHONY : src/input/interaction.i

# target to preprocess a source file
src/input/interaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/input/interaction.cpp.i
.PHONY : src/input/interaction.cpp.i

src/input/interaction.s: src/input/interaction.cpp.s
.PHONY : src/input/interaction.s

# target to generate assembly for a file
src/input/interaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/input/interaction.cpp.s
.PHONY : src/input/interaction.cpp.s

src/input/textEdit.o: src/input/textEdit.cpp.o
.PHONY : src/input/textEdit.o

# target to build an object file
src/input/textEdit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/input/textEdit.cpp.o
.PHONY : src/input/textEdit.cpp.o

src/input/textEdit.i: src/input/textEdit.cpp.i
.PHONY : src/input/textEdit.i

# target to preprocess a source file
src/input/textEdit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/input/textEdit.cpp.i
.PHONY : src/input/textEdit.cpp.i

src/input/textEdit.s: src/input/textEdit.cpp.s
.PHONY : src/input/textEdit.s

# target to generate assembly for a file
src/input/textEdit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/input/textEdit.cpp.s
.PHONY : src/input/textEdit.cpp.s

src/layout/layout.o: src/layout/layout.cpp.o
.PHONY : src/layout/layout.o

# target to build an object file
src/layout/layout.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/layout/layout.cpp.o
.PHONY : src/layout/layout.cpp.o

src/layout/layout.i: src/layout/layout.cpp.i
.PHONY : src/layout/layout.i

# target to preprocess a source file
src/layout/layout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/layout/layout.cpp.i
.PHONY : src/layout/layout.cpp.i

src/layout/layout.s: src/layout/layout.cpp.s
.PHONY : src/layout/layout.s

# target to generate assembly for a file
src/layout/layout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/layout/layout.cpp.s
.PHONY : src/layout/layout.cpp.s

src/layout/textWrap.o: src/layout/textWrap.cpp.o
.PHONY : src/layout/textWrap.o

# target to build an object file
src/layout/textWrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/layout/textWrap.cpp.o
.PHONY : src/layout/textWrap.cpp.o

src/layout/textWrap.i: src/layout/textWrap.cpp.i
.PHONY : src/layout/textWrap.i

# target to preprocess a source file
src/layout/textWrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/layout/textWrap.cpp.i
.PHONY : src/layout/textWrap.cpp.i

src/layout/textWrap.s: src/layout/textWrap.cpp.s
.PHONY : src/layout/textWrap.s

# target to generate assembly for a file
src/layout/textWrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/layout/textWrap.cpp.s
.PHONY : src/layout/textWrap.cpp.s

src/meta/components.o: src/meta/components.cpp.o
.PHONY : src/meta/components.o

# target to build an object file
src/meta/components.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui_meta.dir/build.make CMakeFiles/gbui_meta.dir/src/meta/components.cpp.o
.PHONY : src/meta/components.cpp.o

src/meta/components.i: src/meta/components.cpp.i
.PHONY : src/meta/components.i

# target to preprocess a source file
src/meta/components.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui_meta.dir/build.make CMakeFiles/gbui_meta.dir/src/meta/components.cpp.i
.PHONY : src/meta/components.cpp.i

src/meta/components.s: src/meta/components.cpp.s
.PHONY : src/meta/components.s

# target to generate assembly for a file
src/meta/components.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui_meta.dir/build.make CMakeFiles/gbui_meta.dir/src/meta/components.cpp.s
.PHONY : src/meta/components.cpp.s

src/overlay/placement.o: src/overlay/placement.cpp.o
.PHONY : src/overlay/placement.o

# target to build an object file
src/overlay/placement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/overlay/placement.cpp.o
.PHONY : src/overlay/placement.cpp.o

src/overlay/placement.i: src/overlay/placement.cpp.i
.PHONY : src/overlay/placement.i

# target to preprocess a source file
src/overlay/placement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/overlay/placement.cpp.i
.PHONY : src/overlay/placement.cpp.i

src/overlay/placement.s: src/overlay/placement.cpp.s
.PHONY : src/overlay/placement.s

# target to generate assembly for a file
src/overlay/placement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/overlay/placement.cpp.s
.PHONY : src/overlay/placement.cpp.s

src/paint/canvas.o: src/paint/canvas.cpp.o
.PHONY : src/paint/canvas.o

# target to build an object file
src/paint/canvas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/paint/canvas.cpp.o
.PHONY : src/paint/canvas.cpp.o

src/paint/canvas.i: src/paint/canvas.cpp.i
.PHONY : src/paint/canvas.i

# target to preprocess a source file
src/paint/canvas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/paint/canvas.cpp.i
.PHONY : src/paint/canvas.cpp.i

src/paint/canvas.s: src/paint/canvas.cpp.s
.PHONY : src/paint/canvas.s

# target to generate assembly for a file
src/paint/canvas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/paint/canvas.cpp.s
.PHONY : src/paint/canvas.cpp.s

src/paint/paint.o: src/paint/paint.cpp.o
.PHONY : src/paint/paint.o

# target to build an object file
src/paint/paint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/paint/paint.cpp.o
.PHONY : src/paint/paint.cpp.o

src/paint/paint.i: src/paint/paint.cpp.i
.PHONY : src/paint/paint.i

# target to preprocess a source file
src/paint/paint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/paint/paint.cpp.i
.PHONY : src/paint/paint.cpp.i

src/paint/paint.s: src/paint/paint.cpp.s
.PHONY : src/paint/paint.s

# target to generate assembly for a file
src/paint/paint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/paint/paint.cpp.s
.PHONY : src/paint/paint.cpp.s

src/platform/font.o: src/platform/font.cpp.o
.PHONY : src/platform/font.o

# target to build an object file
src/platform/font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/font.cpp.o
.PHONY : src/platform/font.cpp.o

src/platform/font.i: src/platform/font.cpp.i
.PHONY : src/platform/font.i

# target to preprocess a source file
src/platform/font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/font.cpp.i
.PHONY : src/platform/font.cpp.i

src/platform/font.s: src/platform/font.cpp.s
.PHONY : src/platform/font.s

# target to generate assembly for a file
src/platform/font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/font.cpp.s
.PHONY : src/platform/font.cpp.s

src/platform/image.o: src/platform/image.cpp.o
.PHONY : src/platform/image.o

# target to build an object file
src/platform/image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/image.cpp.o
.PHONY : src/platform/image.cpp.o

src/platform/image.i: src/platform/image.cpp.i
.PHONY : src/platform/image.i

# target to preprocess a source file
src/platform/image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/image.cpp.i
.PHONY : src/platform/image.cpp.i

src/platform/image.s: src/platform/image.cpp.s
.PHONY : src/platform/image.s

# target to generate assembly for a file
src/platform/image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/image.cpp.s
.PHONY : src/platform/image.cpp.s

src/platform/sdl2/window.o: src/platform/sdl2/window.cpp.o
.PHONY : src/platform/sdl2/window.o

# target to build an object file
src/platform/sdl2/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/sdl2/window.cpp.o
.PHONY : src/platform/sdl2/window.cpp.o

src/platform/sdl2/window.i: src/platform/sdl2/window.cpp.i
.PHONY : src/platform/sdl2/window.i

# target to preprocess a source file
src/platform/sdl2/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/sdl2/window.cpp.i
.PHONY : src/platform/sdl2/window.cpp.i

src/platform/sdl2/window.s: src/platform/sdl2/window.cpp.s
.PHONY : src/platform/sdl2/window.s

# target to generate assembly for a file
src/platform/sdl2/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/sdl2/window.cpp.s
.PHONY : src/platform/sdl2/window.cpp.s

src/platform/shell.o: src/platform/shell.cpp.o
.PHONY : src/platform/shell.o

# target to build an object file
src/platform/shell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/shell.cpp.o
.PHONY : src/platform/shell.cpp.o

src/platform/shell.i: src/platform/shell.cpp.i
.PHONY : src/platform/shell.i

# target to preprocess a source file
src/platform/shell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/shell.cpp.i
.PHONY : src/platform/shell.cpp.i

src/platform/shell.s: src/platform/shell.cpp.s
.PHONY : src/platform/shell.s

# target to generate assembly for a file
src/platform/shell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/shell.cpp.s
.PHONY : src/platform/shell.cpp.s

src/platform/stbImageImpl.o: src/platform/stbImageImpl.cpp.o
.PHONY : src/platform/stbImageImpl.o

# target to build an object file
src/platform/stbImageImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/stbImageImpl.cpp.o
.PHONY : src/platform/stbImageImpl.cpp.o

src/platform/stbImageImpl.i: src/platform/stbImageImpl.cpp.i
.PHONY : src/platform/stbImageImpl.i

# target to preprocess a source file
src/platform/stbImageImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/stbImageImpl.cpp.i
.PHONY : src/platform/stbImageImpl.cpp.i

src/platform/stbImageImpl.s: src/platform/stbImageImpl.cpp.s
.PHONY : src/platform/stbImageImpl.s

# target to generate assembly for a file
src/platform/stbImageImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/stbImageImpl.cpp.s
.PHONY : src/platform/stbImageImpl.cpp.s

src/platform/stbTruetypeImpl.o: src/platform/stbTruetypeImpl.cpp.o
.PHONY : src/platform/stbTruetypeImpl.o

# target to build an object file
src/platform/stbTruetypeImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/stbTruetypeImpl.cpp.o
.PHONY : src/platform/stbTruetypeImpl.cpp.o

src/platform/stbTruetypeImpl.i: src/platform/stbTruetypeImpl.cpp.i
.PHONY : src/platform/stbTruetypeImpl.i

# target to preprocess a source file
src/platform/stbTruetypeImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/stbTruetypeImpl.cpp.i
.PHONY : src/platform/stbTruetypeImpl.cpp.i

src/platform/stbTruetypeImpl.s: src/platform/stbTruetypeImpl.cpp.s
.PHONY : src/platform/stbTruetypeImpl.s

# target to generate assembly for a file
src/platform/stbTruetypeImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/platform/stbTruetypeImpl.cpp.s
.PHONY : src/platform/stbTruetypeImpl.cpp.s

src/scene/tree.o: src/scene/tree.cpp.o
.PHONY : src/scene/tree.o

# target to build an object file
src/scene/tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/scene/tree.cpp.o
.PHONY : src/scene/tree.cpp.o

src/scene/tree.i: src/scene/tree.cpp.i
.PHONY : src/scene/tree.i

# target to preprocess a source file
src/scene/tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/scene/tree.cpp.i
.PHONY : src/scene/tree.cpp.i

src/scene/tree.s: src/scene/tree.cpp.s
.PHONY : src/scene/tree.s

# target to generate assembly for a file
src/scene/tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/scene/tree.cpp.s
.PHONY : src/scene/tree.cpp.s

src/scene/ui.o: src/scene/ui.cpp.o
.PHONY : src/scene/ui.o

# target to build an object file
src/scene/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/scene/ui.cpp.o
.PHONY : src/scene/ui.cpp.o

src/scene/ui.i: src/scene/ui.cpp.i
.PHONY : src/scene/ui.i

# target to preprocess a source file
src/scene/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/scene/ui.cpp.i
.PHONY : src/scene/ui.cpp.i

src/scene/ui.s: src/scene/ui.cpp.s
.PHONY : src/scene/ui.s

# target to generate assembly for a file
src/scene/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/scene/ui.cpp.s
.PHONY : src/scene/ui.cpp.s

src/style/design.o: src/style/design.cpp.o
.PHONY : src/style/design.o

# target to build an object file
src/style/design.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/style/design.cpp.o
.PHONY : src/style/design.cpp.o

src/style/design.i: src/style/design.cpp.i
.PHONY : src/style/design.i

# target to preprocess a source file
src/style/design.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/style/design.cpp.i
.PHONY : src/style/design.cpp.i

src/style/design.s: src/style/design.cpp.s
.PHONY : src/style/design.s

# target to generate assembly for a file
src/style/design.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/style/design.cpp.s
.PHONY : src/style/design.cpp.s

src/style/theme.o: src/style/theme.cpp.o
.PHONY : src/style/theme.o

# target to build an object file
src/style/theme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/style/theme.cpp.o
.PHONY : src/style/theme.cpp.o

src/style/theme.i: src/style/theme.cpp.i
.PHONY : src/style/theme.i

# target to preprocess a source file
src/style/theme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/style/theme.cpp.i
.PHONY : src/style/theme.cpp.i

src/style/theme.s: src/style/theme.cpp.s
.PHONY : src/style/theme.s

# target to generate assembly for a file
src/style/theme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/style/theme.cpp.s
.PHONY : src/style/theme.cpp.s

src/widgets/badge.o: src/widgets/badge.cpp.o
.PHONY : src/widgets/badge.o

# target to build an object file
src/widgets/badge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/badge.cpp.o
.PHONY : src/widgets/badge.cpp.o

src/widgets/badge.i: src/widgets/badge.cpp.i
.PHONY : src/widgets/badge.i

# target to preprocess a source file
src/widgets/badge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/badge.cpp.i
.PHONY : src/widgets/badge.cpp.i

src/widgets/badge.s: src/widgets/badge.cpp.s
.PHONY : src/widgets/badge.s

# target to generate assembly for a file
src/widgets/badge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/badge.cpp.s
.PHONY : src/widgets/badge.cpp.s

src/widgets/box.o: src/widgets/box.cpp.o
.PHONY : src/widgets/box.o

# target to build an object file
src/widgets/box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/box.cpp.o
.PHONY : src/widgets/box.cpp.o

src/widgets/box.i: src/widgets/box.cpp.i
.PHONY : src/widgets/box.i

# target to preprocess a source file
src/widgets/box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/box.cpp.i
.PHONY : src/widgets/box.cpp.i

src/widgets/box.s: src/widgets/box.cpp.s
.PHONY : src/widgets/box.s

# target to generate assembly for a file
src/widgets/box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/box.cpp.s
.PHONY : src/widgets/box.cpp.s

src/widgets/button.o: src/widgets/button.cpp.o
.PHONY : src/widgets/button.o

# target to build an object file
src/widgets/button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/button.cpp.o
.PHONY : src/widgets/button.cpp.o

src/widgets/button.i: src/widgets/button.cpp.i
.PHONY : src/widgets/button.i

# target to preprocess a source file
src/widgets/button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/button.cpp.i
.PHONY : src/widgets/button.cpp.i

src/widgets/button.s: src/widgets/button.cpp.s
.PHONY : src/widgets/button.s

# target to generate assembly for a file
src/widgets/button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/button.cpp.s
.PHONY : src/widgets/button.cpp.s

src/widgets/carousel.o: src/widgets/carousel.cpp.o
.PHONY : src/widgets/carousel.o

# target to build an object file
src/widgets/carousel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/carousel.cpp.o
.PHONY : src/widgets/carousel.cpp.o

src/widgets/carousel.i: src/widgets/carousel.cpp.i
.PHONY : src/widgets/carousel.i

# target to preprocess a source file
src/widgets/carousel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/carousel.cpp.i
.PHONY : src/widgets/carousel.cpp.i

src/widgets/carousel.s: src/widgets/carousel.cpp.s
.PHONY : src/widgets/carousel.s

# target to generate assembly for a file
src/widgets/carousel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/carousel.cpp.s
.PHONY : src/widgets/carousel.cpp.s

src/widgets/chart.o: src/widgets/chart.cpp.o
.PHONY : src/widgets/chart.o

# target to build an object file
src/widgets/chart.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/chart.cpp.o
.PHONY : src/widgets/chart.cpp.o

src/widgets/chart.i: src/widgets/chart.cpp.i
.PHONY : src/widgets/chart.i

# target to preprocess a source file
src/widgets/chart.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/chart.cpp.i
.PHONY : src/widgets/chart.cpp.i

src/widgets/chart.s: src/widgets/chart.cpp.s
.PHONY : src/widgets/chart.s

# target to generate assembly for a file
src/widgets/chart.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/chart.cpp.s
.PHONY : src/widgets/chart.cpp.s

src/widgets/checkbox.o: src/widgets/checkbox.cpp.o
.PHONY : src/widgets/checkbox.o

# target to build an object file
src/widgets/checkbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/checkbox.cpp.o
.PHONY : src/widgets/checkbox.cpp.o

src/widgets/checkbox.i: src/widgets/checkbox.cpp.i
.PHONY : src/widgets/checkbox.i

# target to preprocess a source file
src/widgets/checkbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/checkbox.cpp.i
.PHONY : src/widgets/checkbox.cpp.i

src/widgets/checkbox.s: src/widgets/checkbox.cpp.s
.PHONY : src/widgets/checkbox.s

# target to generate assembly for a file
src/widgets/checkbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/checkbox.cpp.s
.PHONY : src/widgets/checkbox.cpp.s

src/widgets/colorPicker.o: src/widgets/colorPicker.cpp.o
.PHONY : src/widgets/colorPicker.o

# target to build an object file
src/widgets/colorPicker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/colorPicker.cpp.o
.PHONY : src/widgets/colorPicker.cpp.o

src/widgets/colorPicker.i: src/widgets/colorPicker.cpp.i
.PHONY : src/widgets/colorPicker.i

# target to preprocess a source file
src/widgets/colorPicker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/colorPicker.cpp.i
.PHONY : src/widgets/colorPicker.cpp.i

src/widgets/colorPicker.s: src/widgets/colorPicker.cpp.s
.PHONY : src/widgets/colorPicker.s

# target to generate assembly for a file
src/widgets/colorPicker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/colorPicker.cpp.s
.PHONY : src/widgets/colorPicker.cpp.s

src/widgets/compare.o: src/widgets/compare.cpp.o
.PHONY : src/widgets/compare.o

# target to build an object file
src/widgets/compare.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/compare.cpp.o
.PHONY : src/widgets/compare.cpp.o

src/widgets/compare.i: src/widgets/compare.cpp.i
.PHONY : src/widgets/compare.i

# target to preprocess a source file
src/widgets/compare.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/compare.cpp.i
.PHONY : src/widgets/compare.cpp.i

src/widgets/compare.s: src/widgets/compare.cpp.s
.PHONY : src/widgets/compare.s

# target to generate assembly for a file
src/widgets/compare.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/compare.cpp.s
.PHONY : src/widgets/compare.cpp.s

src/widgets/datePicker.o: src/widgets/datePicker.cpp.o
.PHONY : src/widgets/datePicker.o

# target to build an object file
src/widgets/datePicker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/datePicker.cpp.o
.PHONY : src/widgets/datePicker.cpp.o

src/widgets/datePicker.i: src/widgets/datePicker.cpp.i
.PHONY : src/widgets/datePicker.i

# target to preprocess a source file
src/widgets/datePicker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/datePicker.cpp.i
.PHONY : src/widgets/datePicker.cpp.i

src/widgets/datePicker.s: src/widgets/datePicker.cpp.s
.PHONY : src/widgets/datePicker.s

# target to generate assembly for a file
src/widgets/datePicker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/datePicker.cpp.s
.PHONY : src/widgets/datePicker.cpp.s

src/widgets/dateTimePicker.o: src/widgets/dateTimePicker.cpp.o
.PHONY : src/widgets/dateTimePicker.o

# target to build an object file
src/widgets/dateTimePicker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/dateTimePicker.cpp.o
.PHONY : src/widgets/dateTimePicker.cpp.o

src/widgets/dateTimePicker.i: src/widgets/dateTimePicker.cpp.i
.PHONY : src/widgets/dateTimePicker.i

# target to preprocess a source file
src/widgets/dateTimePicker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/dateTimePicker.cpp.i
.PHONY : src/widgets/dateTimePicker.cpp.i

src/widgets/dateTimePicker.s: src/widgets/dateTimePicker.cpp.s
.PHONY : src/widgets/dateTimePicker.s

# target to generate assembly for a file
src/widgets/dateTimePicker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/dateTimePicker.cpp.s
.PHONY : src/widgets/dateTimePicker.cpp.s

src/widgets/detail.o: src/widgets/detail.cpp.o
.PHONY : src/widgets/detail.o

# target to build an object file
src/widgets/detail.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/detail.cpp.o
.PHONY : src/widgets/detail.cpp.o

src/widgets/detail.i: src/widgets/detail.cpp.i
.PHONY : src/widgets/detail.i

# target to preprocess a source file
src/widgets/detail.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/detail.cpp.i
.PHONY : src/widgets/detail.cpp.i

src/widgets/detail.s: src/widgets/detail.cpp.s
.PHONY : src/widgets/detail.s

# target to generate assembly for a file
src/widgets/detail.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/detail.cpp.s
.PHONY : src/widgets/detail.cpp.s

src/widgets/drawer.o: src/widgets/drawer.cpp.o
.PHONY : src/widgets/drawer.o

# target to build an object file
src/widgets/drawer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/drawer.cpp.o
.PHONY : src/widgets/drawer.cpp.o

src/widgets/drawer.i: src/widgets/drawer.cpp.i
.PHONY : src/widgets/drawer.i

# target to preprocess a source file
src/widgets/drawer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/drawer.cpp.i
.PHONY : src/widgets/drawer.cpp.i

src/widgets/drawer.s: src/widgets/drawer.cpp.s
.PHONY : src/widgets/drawer.s

# target to generate assembly for a file
src/widgets/drawer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/drawer.cpp.s
.PHONY : src/widgets/drawer.cpp.s

src/widgets/field.o: src/widgets/field.cpp.o
.PHONY : src/widgets/field.o

# target to build an object file
src/widgets/field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/field.cpp.o
.PHONY : src/widgets/field.cpp.o

src/widgets/field.i: src/widgets/field.cpp.i
.PHONY : src/widgets/field.i

# target to preprocess a source file
src/widgets/field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/field.cpp.i
.PHONY : src/widgets/field.cpp.i

src/widgets/field.s: src/widgets/field.cpp.s
.PHONY : src/widgets/field.s

# target to generate assembly for a file
src/widgets/field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/field.cpp.s
.PHONY : src/widgets/field.cpp.s

src/widgets/floating.o: src/widgets/floating.cpp.o
.PHONY : src/widgets/floating.o

# target to build an object file
src/widgets/floating.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/floating.cpp.o
.PHONY : src/widgets/floating.cpp.o

src/widgets/floating.i: src/widgets/floating.cpp.i
.PHONY : src/widgets/floating.i

# target to preprocess a source file
src/widgets/floating.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/floating.cpp.i
.PHONY : src/widgets/floating.cpp.i

src/widgets/floating.s: src/widgets/floating.cpp.s
.PHONY : src/widgets/floating.s

# target to generate assembly for a file
src/widgets/floating.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/floating.cpp.s
.PHONY : src/widgets/floating.cpp.s

src/widgets/gallery.o: src/widgets/gallery.cpp.o
.PHONY : src/widgets/gallery.o

# target to build an object file
src/widgets/gallery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/gallery.cpp.o
.PHONY : src/widgets/gallery.cpp.o

src/widgets/gallery.i: src/widgets/gallery.cpp.i
.PHONY : src/widgets/gallery.i

# target to preprocess a source file
src/widgets/gallery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/gallery.cpp.i
.PHONY : src/widgets/gallery.cpp.i

src/widgets/gallery.s: src/widgets/gallery.cpp.s
.PHONY : src/widgets/gallery.s

# target to generate assembly for a file
src/widgets/gallery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/gallery.cpp.s
.PHONY : src/widgets/gallery.cpp.s

src/widgets/hyperlink.o: src/widgets/hyperlink.cpp.o
.PHONY : src/widgets/hyperlink.o

# target to build an object file
src/widgets/hyperlink.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/hyperlink.cpp.o
.PHONY : src/widgets/hyperlink.cpp.o

src/widgets/hyperlink.i: src/widgets/hyperlink.cpp.i
.PHONY : src/widgets/hyperlink.i

# target to preprocess a source file
src/widgets/hyperlink.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/hyperlink.cpp.i
.PHONY : src/widgets/hyperlink.cpp.i

src/widgets/hyperlink.s: src/widgets/hyperlink.cpp.s
.PHONY : src/widgets/hyperlink.s

# target to generate assembly for a file
src/widgets/hyperlink.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/hyperlink.cpp.s
.PHONY : src/widgets/hyperlink.cpp.s

src/widgets/icon.o: src/widgets/icon.cpp.o
.PHONY : src/widgets/icon.o

# target to build an object file
src/widgets/icon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/icon.cpp.o
.PHONY : src/widgets/icon.cpp.o

src/widgets/icon.i: src/widgets/icon.cpp.i
.PHONY : src/widgets/icon.i

# target to preprocess a source file
src/widgets/icon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/icon.cpp.i
.PHONY : src/widgets/icon.cpp.i

src/widgets/icon.s: src/widgets/icon.cpp.s
.PHONY : src/widgets/icon.s

# target to generate assembly for a file
src/widgets/icon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/icon.cpp.s
.PHONY : src/widgets/icon.cpp.s

src/widgets/icons.o: src/widgets/icons.cpp.o
.PHONY : src/widgets/icons.o

# target to build an object file
src/widgets/icons.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/icons.cpp.o
.PHONY : src/widgets/icons.cpp.o

src/widgets/icons.i: src/widgets/icons.cpp.i
.PHONY : src/widgets/icons.i

# target to preprocess a source file
src/widgets/icons.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/icons.cpp.i
.PHONY : src/widgets/icons.cpp.i

src/widgets/icons.s: src/widgets/icons.cpp.s
.PHONY : src/widgets/icons.s

# target to generate assembly for a file
src/widgets/icons.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/icons.cpp.s
.PHONY : src/widgets/icons.cpp.s

src/widgets/image.o: src/widgets/image.cpp.o
.PHONY : src/widgets/image.o

# target to build an object file
src/widgets/image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/image.cpp.o
.PHONY : src/widgets/image.cpp.o

src/widgets/image.i: src/widgets/image.cpp.i
.PHONY : src/widgets/image.i

# target to preprocess a source file
src/widgets/image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/image.cpp.i
.PHONY : src/widgets/image.cpp.i

src/widgets/image.s: src/widgets/image.cpp.s
.PHONY : src/widgets/image.s

# target to generate assembly for a file
src/widgets/image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/image.cpp.s
.PHONY : src/widgets/image.cpp.s

src/widgets/label.o: src/widgets/label.cpp.o
.PHONY : src/widgets/label.o

# target to build an object file
src/widgets/label.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/label.cpp.o
.PHONY : src/widgets/label.cpp.o

src/widgets/label.i: src/widgets/label.cpp.i
.PHONY : src/widgets/label.i

# target to preprocess a source file
src/widgets/label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/label.cpp.i
.PHONY : src/widgets/label.cpp.i

src/widgets/label.s: src/widgets/label.cpp.s
.PHONY : src/widgets/label.s

# target to generate assembly for a file
src/widgets/label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/label.cpp.s
.PHONY : src/widgets/label.cpp.s

src/widgets/listRow.o: src/widgets/listRow.cpp.o
.PHONY : src/widgets/listRow.o

# target to build an object file
src/widgets/listRow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/listRow.cpp.o
.PHONY : src/widgets/listRow.cpp.o

src/widgets/listRow.i: src/widgets/listRow.cpp.i
.PHONY : src/widgets/listRow.i

# target to preprocess a source file
src/widgets/listRow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/listRow.cpp.i
.PHONY : src/widgets/listRow.cpp.i

src/widgets/listRow.s: src/widgets/listRow.cpp.s
.PHONY : src/widgets/listRow.s

# target to generate assembly for a file
src/widgets/listRow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/listRow.cpp.s
.PHONY : src/widgets/listRow.cpp.s

src/widgets/marquee.o: src/widgets/marquee.cpp.o
.PHONY : src/widgets/marquee.o

# target to build an object file
src/widgets/marquee.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/marquee.cpp.o
.PHONY : src/widgets/marquee.cpp.o

src/widgets/marquee.i: src/widgets/marquee.cpp.i
.PHONY : src/widgets/marquee.i

# target to preprocess a source file
src/widgets/marquee.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/marquee.cpp.i
.PHONY : src/widgets/marquee.cpp.i

src/widgets/marquee.s: src/widgets/marquee.cpp.s
.PHONY : src/widgets/marquee.s

# target to generate assembly for a file
src/widgets/marquee.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/marquee.cpp.s
.PHONY : src/widgets/marquee.cpp.s

src/widgets/menu.o: src/widgets/menu.cpp.o
.PHONY : src/widgets/menu.o

# target to build an object file
src/widgets/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/menu.cpp.o
.PHONY : src/widgets/menu.cpp.o

src/widgets/menu.i: src/widgets/menu.cpp.i
.PHONY : src/widgets/menu.i

# target to preprocess a source file
src/widgets/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/menu.cpp.i
.PHONY : src/widgets/menu.cpp.i

src/widgets/menu.s: src/widgets/menu.cpp.s
.PHONY : src/widgets/menu.s

# target to generate assembly for a file
src/widgets/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/menu.cpp.s
.PHONY : src/widgets/menu.cpp.s

src/widgets/modal.o: src/widgets/modal.cpp.o
.PHONY : src/widgets/modal.o

# target to build an object file
src/widgets/modal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/modal.cpp.o
.PHONY : src/widgets/modal.cpp.o

src/widgets/modal.i: src/widgets/modal.cpp.i
.PHONY : src/widgets/modal.i

# target to preprocess a source file
src/widgets/modal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/modal.cpp.i
.PHONY : src/widgets/modal.cpp.i

src/widgets/modal.s: src/widgets/modal.cpp.s
.PHONY : src/widgets/modal.s

# target to generate assembly for a file
src/widgets/modal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/modal.cpp.s
.PHONY : src/widgets/modal.cpp.s

src/widgets/panel.o: src/widgets/panel.cpp.o
.PHONY : src/widgets/panel.o

# target to build an object file
src/widgets/panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/panel.cpp.o
.PHONY : src/widgets/panel.cpp.o

src/widgets/panel.i: src/widgets/panel.cpp.i
.PHONY : src/widgets/panel.i

# target to preprocess a source file
src/widgets/panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/panel.cpp.i
.PHONY : src/widgets/panel.cpp.i

src/widgets/panel.s: src/widgets/panel.cpp.s
.PHONY : src/widgets/panel.s

# target to generate assembly for a file
src/widgets/panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/panel.cpp.s
.PHONY : src/widgets/panel.cpp.s

src/widgets/popover.o: src/widgets/popover.cpp.o
.PHONY : src/widgets/popover.o

# target to build an object file
src/widgets/popover.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/popover.cpp.o
.PHONY : src/widgets/popover.cpp.o

src/widgets/popover.i: src/widgets/popover.cpp.i
.PHONY : src/widgets/popover.i

# target to preprocess a source file
src/widgets/popover.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/popover.cpp.i
.PHONY : src/widgets/popover.cpp.i

src/widgets/popover.s: src/widgets/popover.cpp.s
.PHONY : src/widgets/popover.s

# target to generate assembly for a file
src/widgets/popover.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/popover.cpp.s
.PHONY : src/widgets/popover.cpp.s

src/widgets/progress.o: src/widgets/progress.cpp.o
.PHONY : src/widgets/progress.o

# target to build an object file
src/widgets/progress.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/progress.cpp.o
.PHONY : src/widgets/progress.cpp.o

src/widgets/progress.i: src/widgets/progress.cpp.i
.PHONY : src/widgets/progress.i

# target to preprocess a source file
src/widgets/progress.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/progress.cpp.i
.PHONY : src/widgets/progress.cpp.i

src/widgets/progress.s: src/widgets/progress.cpp.s
.PHONY : src/widgets/progress.s

# target to generate assembly for a file
src/widgets/progress.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/progress.cpp.s
.PHONY : src/widgets/progress.cpp.s

src/widgets/radio.o: src/widgets/radio.cpp.o
.PHONY : src/widgets/radio.o

# target to build an object file
src/widgets/radio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/radio.cpp.o
.PHONY : src/widgets/radio.cpp.o

src/widgets/radio.i: src/widgets/radio.cpp.i
.PHONY : src/widgets/radio.i

# target to preprocess a source file
src/widgets/radio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/radio.cpp.i
.PHONY : src/widgets/radio.cpp.i

src/widgets/radio.s: src/widgets/radio.cpp.s
.PHONY : src/widgets/radio.s

# target to generate assembly for a file
src/widgets/radio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/radio.cpp.s
.PHONY : src/widgets/radio.cpp.s

src/widgets/richEditor.o: src/widgets/richEditor.cpp.o
.PHONY : src/widgets/richEditor.o

# target to build an object file
src/widgets/richEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/richEditor.cpp.o
.PHONY : src/widgets/richEditor.cpp.o

src/widgets/richEditor.i: src/widgets/richEditor.cpp.i
.PHONY : src/widgets/richEditor.i

# target to preprocess a source file
src/widgets/richEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/richEditor.cpp.i
.PHONY : src/widgets/richEditor.cpp.i

src/widgets/richEditor.s: src/widgets/richEditor.cpp.s
.PHONY : src/widgets/richEditor.s

# target to generate assembly for a file
src/widgets/richEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/richEditor.cpp.s
.PHONY : src/widgets/richEditor.cpp.s

src/widgets/scroll.o: src/widgets/scroll.cpp.o
.PHONY : src/widgets/scroll.o

# target to build an object file
src/widgets/scroll.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/scroll.cpp.o
.PHONY : src/widgets/scroll.cpp.o

src/widgets/scroll.i: src/widgets/scroll.cpp.i
.PHONY : src/widgets/scroll.i

# target to preprocess a source file
src/widgets/scroll.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/scroll.cpp.i
.PHONY : src/widgets/scroll.cpp.i

src/widgets/scroll.s: src/widgets/scroll.cpp.s
.PHONY : src/widgets/scroll.s

# target to generate assembly for a file
src/widgets/scroll.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/scroll.cpp.s
.PHONY : src/widgets/scroll.cpp.s

src/widgets/select.o: src/widgets/select.cpp.o
.PHONY : src/widgets/select.o

# target to build an object file
src/widgets/select.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/select.cpp.o
.PHONY : src/widgets/select.cpp.o

src/widgets/select.i: src/widgets/select.cpp.i
.PHONY : src/widgets/select.i

# target to preprocess a source file
src/widgets/select.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/select.cpp.i
.PHONY : src/widgets/select.cpp.i

src/widgets/select.s: src/widgets/select.cpp.s
.PHONY : src/widgets/select.s

# target to generate assembly for a file
src/widgets/select.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/select.cpp.s
.PHONY : src/widgets/select.cpp.s

src/widgets/slider.o: src/widgets/slider.cpp.o
.PHONY : src/widgets/slider.o

# target to build an object file
src/widgets/slider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/slider.cpp.o
.PHONY : src/widgets/slider.cpp.o

src/widgets/slider.i: src/widgets/slider.cpp.i
.PHONY : src/widgets/slider.i

# target to preprocess a source file
src/widgets/slider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/slider.cpp.i
.PHONY : src/widgets/slider.cpp.i

src/widgets/slider.s: src/widgets/slider.cpp.s
.PHONY : src/widgets/slider.s

# target to generate assembly for a file
src/widgets/slider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/slider.cpp.s
.PHONY : src/widgets/slider.cpp.s

src/widgets/spacing.o: src/widgets/spacing.cpp.o
.PHONY : src/widgets/spacing.o

# target to build an object file
src/widgets/spacing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/spacing.cpp.o
.PHONY : src/widgets/spacing.cpp.o

src/widgets/spacing.i: src/widgets/spacing.cpp.i
.PHONY : src/widgets/spacing.i

# target to preprocess a source file
src/widgets/spacing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/spacing.cpp.i
.PHONY : src/widgets/spacing.cpp.i

src/widgets/spacing.s: src/widgets/spacing.cpp.s
.PHONY : src/widgets/spacing.s

# target to generate assembly for a file
src/widgets/spacing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/spacing.cpp.s
.PHONY : src/widgets/spacing.cpp.s

src/widgets/splitPane.o: src/widgets/splitPane.cpp.o
.PHONY : src/widgets/splitPane.o

# target to build an object file
src/widgets/splitPane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/splitPane.cpp.o
.PHONY : src/widgets/splitPane.cpp.o

src/widgets/splitPane.i: src/widgets/splitPane.cpp.i
.PHONY : src/widgets/splitPane.i

# target to preprocess a source file
src/widgets/splitPane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/splitPane.cpp.i
.PHONY : src/widgets/splitPane.cpp.i

src/widgets/splitPane.s: src/widgets/splitPane.cpp.s
.PHONY : src/widgets/splitPane.s

# target to generate assembly for a file
src/widgets/splitPane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/splitPane.cpp.s
.PHONY : src/widgets/splitPane.cpp.s

src/widgets/table.o: src/widgets/table.cpp.o
.PHONY : src/widgets/table.o

# target to build an object file
src/widgets/table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/table.cpp.o
.PHONY : src/widgets/table.cpp.o

src/widgets/table.i: src/widgets/table.cpp.i
.PHONY : src/widgets/table.i

# target to preprocess a source file
src/widgets/table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/table.cpp.i
.PHONY : src/widgets/table.cpp.i

src/widgets/table.s: src/widgets/table.cpp.s
.PHONY : src/widgets/table.s

# target to generate assembly for a file
src/widgets/table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/table.cpp.s
.PHONY : src/widgets/table.cpp.s

src/widgets/tabs.o: src/widgets/tabs.cpp.o
.PHONY : src/widgets/tabs.o

# target to build an object file
src/widgets/tabs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/tabs.cpp.o
.PHONY : src/widgets/tabs.cpp.o

src/widgets/tabs.i: src/widgets/tabs.cpp.i
.PHONY : src/widgets/tabs.i

# target to preprocess a source file
src/widgets/tabs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/tabs.cpp.i
.PHONY : src/widgets/tabs.cpp.i

src/widgets/tabs.s: src/widgets/tabs.cpp.s
.PHONY : src/widgets/tabs.s

# target to generate assembly for a file
src/widgets/tabs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/tabs.cpp.s
.PHONY : src/widgets/tabs.cpp.s

src/widgets/text.o: src/widgets/text.cpp.o
.PHONY : src/widgets/text.o

# target to build an object file
src/widgets/text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/text.cpp.o
.PHONY : src/widgets/text.cpp.o

src/widgets/text.i: src/widgets/text.cpp.i
.PHONY : src/widgets/text.i

# target to preprocess a source file
src/widgets/text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/text.cpp.i
.PHONY : src/widgets/text.cpp.i

src/widgets/text.s: src/widgets/text.cpp.s
.PHONY : src/widgets/text.s

# target to generate assembly for a file
src/widgets/text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/text.cpp.s
.PHONY : src/widgets/text.cpp.s

src/widgets/textInput.o: src/widgets/textInput.cpp.o
.PHONY : src/widgets/textInput.o

# target to build an object file
src/widgets/textInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/textInput.cpp.o
.PHONY : src/widgets/textInput.cpp.o

src/widgets/textInput.i: src/widgets/textInput.cpp.i
.PHONY : src/widgets/textInput.i

# target to preprocess a source file
src/widgets/textInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/textInput.cpp.i
.PHONY : src/widgets/textInput.cpp.i

src/widgets/textInput.s: src/widgets/textInput.cpp.s
.PHONY : src/widgets/textInput.s

# target to generate assembly for a file
src/widgets/textInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/textInput.cpp.s
.PHONY : src/widgets/textInput.cpp.s

src/widgets/textarea.o: src/widgets/textarea.cpp.o
.PHONY : src/widgets/textarea.o

# target to build an object file
src/widgets/textarea.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/textarea.cpp.o
.PHONY : src/widgets/textarea.cpp.o

src/widgets/textarea.i: src/widgets/textarea.cpp.i
.PHONY : src/widgets/textarea.i

# target to preprocess a source file
src/widgets/textarea.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/textarea.cpp.i
.PHONY : src/widgets/textarea.cpp.i

src/widgets/textarea.s: src/widgets/textarea.cpp.s
.PHONY : src/widgets/textarea.s

# target to generate assembly for a file
src/widgets/textarea.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/textarea.cpp.s
.PHONY : src/widgets/textarea.cpp.s

src/widgets/timePicker.o: src/widgets/timePicker.cpp.o
.PHONY : src/widgets/timePicker.o

# target to build an object file
src/widgets/timePicker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/timePicker.cpp.o
.PHONY : src/widgets/timePicker.cpp.o

src/widgets/timePicker.i: src/widgets/timePicker.cpp.i
.PHONY : src/widgets/timePicker.i

# target to preprocess a source file
src/widgets/timePicker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/timePicker.cpp.i
.PHONY : src/widgets/timePicker.cpp.i

src/widgets/timePicker.s: src/widgets/timePicker.cpp.s
.PHONY : src/widgets/timePicker.s

# target to generate assembly for a file
src/widgets/timePicker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/timePicker.cpp.s
.PHONY : src/widgets/timePicker.cpp.s

src/widgets/toast.o: src/widgets/toast.cpp.o
.PHONY : src/widgets/toast.o

# target to build an object file
src/widgets/toast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/toast.cpp.o
.PHONY : src/widgets/toast.cpp.o

src/widgets/toast.i: src/widgets/toast.cpp.i
.PHONY : src/widgets/toast.i

# target to preprocess a source file
src/widgets/toast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/toast.cpp.i
.PHONY : src/widgets/toast.cpp.i

src/widgets/toast.s: src/widgets/toast.cpp.s
.PHONY : src/widgets/toast.s

# target to generate assembly for a file
src/widgets/toast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/toast.cpp.s
.PHONY : src/widgets/toast.cpp.s

src/widgets/toggle.o: src/widgets/toggle.cpp.o
.PHONY : src/widgets/toggle.o

# target to build an object file
src/widgets/toggle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/toggle.cpp.o
.PHONY : src/widgets/toggle.cpp.o

src/widgets/toggle.i: src/widgets/toggle.cpp.i
.PHONY : src/widgets/toggle.i

# target to preprocess a source file
src/widgets/toggle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/toggle.cpp.i
.PHONY : src/widgets/toggle.cpp.i

src/widgets/toggle.s: src/widgets/toggle.cpp.s
.PHONY : src/widgets/toggle.s

# target to generate assembly for a file
src/widgets/toggle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/toggle.cpp.s
.PHONY : src/widgets/toggle.cpp.s

src/widgets/toolbar.o: src/widgets/toolbar.cpp.o
.PHONY : src/widgets/toolbar.o

# target to build an object file
src/widgets/toolbar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/toolbar.cpp.o
.PHONY : src/widgets/toolbar.cpp.o

src/widgets/toolbar.i: src/widgets/toolbar.cpp.i
.PHONY : src/widgets/toolbar.i

# target to preprocess a source file
src/widgets/toolbar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/toolbar.cpp.i
.PHONY : src/widgets/toolbar.cpp.i

src/widgets/toolbar.s: src/widgets/toolbar.cpp.s
.PHONY : src/widgets/toolbar.s

# target to generate assembly for a file
src/widgets/toolbar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/toolbar.cpp.s
.PHONY : src/widgets/toolbar.cpp.s

src/widgets/tooltip.o: src/widgets/tooltip.cpp.o
.PHONY : src/widgets/tooltip.o

# target to build an object file
src/widgets/tooltip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/tooltip.cpp.o
.PHONY : src/widgets/tooltip.cpp.o

src/widgets/tooltip.i: src/widgets/tooltip.cpp.i
.PHONY : src/widgets/tooltip.i

# target to preprocess a source file
src/widgets/tooltip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/tooltip.cpp.i
.PHONY : src/widgets/tooltip.cpp.i

src/widgets/tooltip.s: src/widgets/tooltip.cpp.s
.PHONY : src/widgets/tooltip.s

# target to generate assembly for a file
src/widgets/tooltip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/tooltip.cpp.s
.PHONY : src/widgets/tooltip.cpp.s

src/widgets/treeView.o: src/widgets/treeView.cpp.o
.PHONY : src/widgets/treeView.o

# target to build an object file
src/widgets/treeView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/treeView.cpp.o
.PHONY : src/widgets/treeView.cpp.o

src/widgets/treeView.i: src/widgets/treeView.cpp.i
.PHONY : src/widgets/treeView.i

# target to preprocess a source file
src/widgets/treeView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/treeView.cpp.i
.PHONY : src/widgets/treeView.cpp.i

src/widgets/treeView.s: src/widgets/treeView.cpp.s
.PHONY : src/widgets/treeView.s

# target to generate assembly for a file
src/widgets/treeView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/treeView.cpp.s
.PHONY : src/widgets/treeView.cpp.s

src/widgets/virtualList.o: src/widgets/virtualList.cpp.o
.PHONY : src/widgets/virtualList.o

# target to build an object file
src/widgets/virtualList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/virtualList.cpp.o
.PHONY : src/widgets/virtualList.cpp.o

src/widgets/virtualList.i: src/widgets/virtualList.cpp.i
.PHONY : src/widgets/virtualList.i

# target to preprocess a source file
src/widgets/virtualList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/virtualList.cpp.i
.PHONY : src/widgets/virtualList.cpp.i

src/widgets/virtualList.s: src/widgets/virtualList.cpp.s
.PHONY : src/widgets/virtualList.s

# target to generate assembly for a file
src/widgets/virtualList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gbui.dir/build.make CMakeFiles/gbui.dir/src/widgets/virtualList.cpp.s
.PHONY : src/widgets/virtualList.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gbui"
	@echo "... gbui_app"
	@echo "... gbui_controls"
	@echo "... gbui_demo"
	@echo "... gbui_demos"
	@echo "... gbui_gallery"
	@echo "... gbui_meta"
	@echo "... gbui_panel"
	@echo "... gbui_tests"
	@echo "... src/a11y/role.o"
	@echo "... src/a11y/role.i"
	@echo "... src/a11y/role.s"
	@echo "... src/a11y/tree.o"
	@echo "... src/a11y/tree.i"
	@echo "... src/a11y/tree.s"
	@echo "... src/anim/animator.o"
	@echo "... src/anim/animator.i"
	@echo "... src/anim/animator.s"
	@echo "... src/anim/easing.o"
	@echo "... src/anim/easing.i"
	@echo "... src/anim/easing.s"
	@echo "... src/core/color.o"
	@echo "... src/core/color.i"
	@echo "... src/core/color.s"
	@echo "... src/core/json.o"
	@echo "... src/core/json.i"
	@echo "... src/core/json.s"
	@echo "... src/core/path.o"
	@echo "... src/core/path.i"
	@echo "... src/core/path.s"
	@echo "... src/input/interaction.o"
	@echo "... src/input/interaction.i"
	@echo "... src/input/interaction.s"
	@echo "... src/input/textEdit.o"
	@echo "... src/input/textEdit.i"
	@echo "... src/input/textEdit.s"
	@echo "... src/layout/layout.o"
	@echo "... src/layout/layout.i"
	@echo "... src/layout/layout.s"
	@echo "... src/layout/textWrap.o"
	@echo "... src/layout/textWrap.i"
	@echo "... src/layout/textWrap.s"
	@echo "... src/meta/components.o"
	@echo "... src/meta/components.i"
	@echo "... src/meta/components.s"
	@echo "... src/overlay/placement.o"
	@echo "... src/overlay/placement.i"
	@echo "... src/overlay/placement.s"
	@echo "... src/paint/canvas.o"
	@echo "... src/paint/canvas.i"
	@echo "... src/paint/canvas.s"
	@echo "... src/paint/paint.o"
	@echo "... src/paint/paint.i"
	@echo "... src/paint/paint.s"
	@echo "... src/platform/font.o"
	@echo "... src/platform/font.i"
	@echo "... src/platform/font.s"
	@echo "... src/platform/image.o"
	@echo "... src/platform/image.i"
	@echo "... src/platform/image.s"
	@echo "... src/platform/sdl2/window.o"
	@echo "... src/platform/sdl2/window.i"
	@echo "... src/platform/sdl2/window.s"
	@echo "... src/platform/shell.o"
	@echo "... src/platform/shell.i"
	@echo "... src/platform/shell.s"
	@echo "... src/platform/stbImageImpl.o"
	@echo "... src/platform/stbImageImpl.i"
	@echo "... src/platform/stbImageImpl.s"
	@echo "... src/platform/stbTruetypeImpl.o"
	@echo "... src/platform/stbTruetypeImpl.i"
	@echo "... src/platform/stbTruetypeImpl.s"
	@echo "... src/scene/tree.o"
	@echo "... src/scene/tree.i"
	@echo "... src/scene/tree.s"
	@echo "... src/scene/ui.o"
	@echo "... src/scene/ui.i"
	@echo "... src/scene/ui.s"
	@echo "... src/style/design.o"
	@echo "... src/style/design.i"
	@echo "... src/style/design.s"
	@echo "... src/style/theme.o"
	@echo "... src/style/theme.i"
	@echo "... src/style/theme.s"
	@echo "... src/widgets/badge.o"
	@echo "... src/widgets/badge.i"
	@echo "... src/widgets/badge.s"
	@echo "... src/widgets/box.o"
	@echo "... src/widgets/box.i"
	@echo "... src/widgets/box.s"
	@echo "... src/widgets/button.o"
	@echo "... src/widgets/button.i"
	@echo "... src/widgets/button.s"
	@echo "... src/widgets/carousel.o"
	@echo "... src/widgets/carousel.i"
	@echo "... src/widgets/carousel.s"
	@echo "... src/widgets/chart.o"
	@echo "... src/widgets/chart.i"
	@echo "... src/widgets/chart.s"
	@echo "... src/widgets/checkbox.o"
	@echo "... src/widgets/checkbox.i"
	@echo "... src/widgets/checkbox.s"
	@echo "... src/widgets/colorPicker.o"
	@echo "... src/widgets/colorPicker.i"
	@echo "... src/widgets/colorPicker.s"
	@echo "... src/widgets/compare.o"
	@echo "... src/widgets/compare.i"
	@echo "... src/widgets/compare.s"
	@echo "... src/widgets/datePicker.o"
	@echo "... src/widgets/datePicker.i"
	@echo "... src/widgets/datePicker.s"
	@echo "... src/widgets/dateTimePicker.o"
	@echo "... src/widgets/dateTimePicker.i"
	@echo "... src/widgets/dateTimePicker.s"
	@echo "... src/widgets/detail.o"
	@echo "... src/widgets/detail.i"
	@echo "... src/widgets/detail.s"
	@echo "... src/widgets/drawer.o"
	@echo "... src/widgets/drawer.i"
	@echo "... src/widgets/drawer.s"
	@echo "... src/widgets/field.o"
	@echo "... src/widgets/field.i"
	@echo "... src/widgets/field.s"
	@echo "... src/widgets/floating.o"
	@echo "... src/widgets/floating.i"
	@echo "... src/widgets/floating.s"
	@echo "... src/widgets/gallery.o"
	@echo "... src/widgets/gallery.i"
	@echo "... src/widgets/gallery.s"
	@echo "... src/widgets/hyperlink.o"
	@echo "... src/widgets/hyperlink.i"
	@echo "... src/widgets/hyperlink.s"
	@echo "... src/widgets/icon.o"
	@echo "... src/widgets/icon.i"
	@echo "... src/widgets/icon.s"
	@echo "... src/widgets/icons.o"
	@echo "... src/widgets/icons.i"
	@echo "... src/widgets/icons.s"
	@echo "... src/widgets/image.o"
	@echo "... src/widgets/image.i"
	@echo "... src/widgets/image.s"
	@echo "... src/widgets/label.o"
	@echo "... src/widgets/label.i"
	@echo "... src/widgets/label.s"
	@echo "... src/widgets/listRow.o"
	@echo "... src/widgets/listRow.i"
	@echo "... src/widgets/listRow.s"
	@echo "... src/widgets/marquee.o"
	@echo "... src/widgets/marquee.i"
	@echo "... src/widgets/marquee.s"
	@echo "... src/widgets/menu.o"
	@echo "... src/widgets/menu.i"
	@echo "... src/widgets/menu.s"
	@echo "... src/widgets/modal.o"
	@echo "... src/widgets/modal.i"
	@echo "... src/widgets/modal.s"
	@echo "... src/widgets/panel.o"
	@echo "... src/widgets/panel.i"
	@echo "... src/widgets/panel.s"
	@echo "... src/widgets/popover.o"
	@echo "... src/widgets/popover.i"
	@echo "... src/widgets/popover.s"
	@echo "... src/widgets/progress.o"
	@echo "... src/widgets/progress.i"
	@echo "... src/widgets/progress.s"
	@echo "... src/widgets/radio.o"
	@echo "... src/widgets/radio.i"
	@echo "... src/widgets/radio.s"
	@echo "... src/widgets/richEditor.o"
	@echo "... src/widgets/richEditor.i"
	@echo "... src/widgets/richEditor.s"
	@echo "... src/widgets/scroll.o"
	@echo "... src/widgets/scroll.i"
	@echo "... src/widgets/scroll.s"
	@echo "... src/widgets/select.o"
	@echo "... src/widgets/select.i"
	@echo "... src/widgets/select.s"
	@echo "... src/widgets/slider.o"
	@echo "... src/widgets/slider.i"
	@echo "... src/widgets/slider.s"
	@echo "... src/widgets/spacing.o"
	@echo "... src/widgets/spacing.i"
	@echo "... src/widgets/spacing.s"
	@echo "... src/widgets/splitPane.o"
	@echo "... src/widgets/splitPane.i"
	@echo "... src/widgets/splitPane.s"
	@echo "... src/widgets/table.o"
	@echo "... src/widgets/table.i"
	@echo "... src/widgets/table.s"
	@echo "... src/widgets/tabs.o"
	@echo "... src/widgets/tabs.i"
	@echo "... src/widgets/tabs.s"
	@echo "... src/widgets/text.o"
	@echo "... src/widgets/text.i"
	@echo "... src/widgets/text.s"
	@echo "... src/widgets/textInput.o"
	@echo "... src/widgets/textInput.i"
	@echo "... src/widgets/textInput.s"
	@echo "... src/widgets/textarea.o"
	@echo "... src/widgets/textarea.i"
	@echo "... src/widgets/textarea.s"
	@echo "... src/widgets/timePicker.o"
	@echo "... src/widgets/timePicker.i"
	@echo "... src/widgets/timePicker.s"
	@echo "... src/widgets/toast.o"
	@echo "... src/widgets/toast.i"
	@echo "... src/widgets/toast.s"
	@echo "... src/widgets/toggle.o"
	@echo "... src/widgets/toggle.i"
	@echo "... src/widgets/toggle.s"
	@echo "... src/widgets/toolbar.o"
	@echo "... src/widgets/toolbar.i"
	@echo "... src/widgets/toolbar.s"
	@echo "... src/widgets/tooltip.o"
	@echo "... src/widgets/tooltip.i"
	@echo "... src/widgets/tooltip.s"
	@echo "... src/widgets/treeView.o"
	@echo "... src/widgets/treeView.i"
	@echo "... src/widgets/treeView.s"
	@echo "... src/widgets/virtualList.o"
	@echo "... src/widgets/virtualList.i"
	@echo "... src/widgets/virtualList.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

